# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: jbook_Proyecto_Final_Clasificacion
author: Angélica Sepúlveda, Andrés Pedraza y Jefry Llerena 
language: es
logo: logo-uninorte.png
only_build_toc_files: true

execute:
  execute_notebooks: "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: proyecto_final_clasificacion.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book
  path_to_book: docs2
  branch: master

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
